
public class DialAyuda extends javax.swing.JDialog {

    /**
     * Creates new form DialAyuda
     */
    public DialAyuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ayuda");
        setResizable(false);

        lblInfo.setText("<html>Este programa permite obtener los valores<br>"
            + "menores que un cierto umbral a partir de una<br>"
            + "lista de datos desordenados y muestra por pantalla<br>"
            + "los resultados obtenidos ordenados de mayor a<br>"
            + "menor. El umbral debe ser uno de los valores de<br>"
            + "la lista original.<br><br>"
            + "Además, está disponible la opción de visualizar<br>"
            + "el vector en orden ascendente.<br><br>"
            + "El umbral debe ser un número real contenido en el<br>"
            + "vector. La separación decimal debe de estar<br>"
            + "representada por un punto.<br><br>"
            + "Para permitir la inserción de un umbral válido<br>"
            + "se muestra el vector en el botón: 'Mostrar vector'.</html>");
        lblInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        getContentPane().add(lblInfo, java.awt.BorderLayout.CENTER);

        lblGrupo.setText("<html>Equipo 12<br>"
            + "(Viernes 10:30-12:30)</html>");
        lblGrupo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        getContentPane().add(lblGrupo, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables
}
