
import com.sun.glass.events.KeyEvent;
import java.text.NumberFormat;
import java.text.ParsePosition;

public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUmbral = new javax.swing.JPanel();
        lblUmbral = new javax.swing.JLabel();
        txtUmbral = new javax.swing.JTextField();
        btnEstablecer = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        separatorUmbralResultado = new javax.swing.JSeparator();
        lblAyuda = new javax.swing.JLabel();
        panelResultado = new javax.swing.JPanel();
        scrollValores = new javax.swing.JScrollPane();
        txtValores = new javax.swing.JTextArea();
        checkOrdenar = new javax.swing.JCheckBox();
        lblValores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Valores menores que un umbral");
        setResizable(false);

        panelUmbral.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 10));

        lblUmbral.setText("Umbral");

        txtUmbral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUmbralKeyPressed(evt);
            }
        });

        btnEstablecer.setText("Establecer");
        btnEstablecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstablecerMouseClicked(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(206, 0, 0));
        lblError.setText("    ");

        separatorUmbralResultado.setForeground(new java.awt.Color(185, 185, 185));

        lblAyuda.setText("?");

        javax.swing.GroupLayout panelUmbralLayout = new javax.swing.GroupLayout(panelUmbral);
        panelUmbral.setLayout(panelUmbralLayout);
        panelUmbralLayout.setHorizontalGroup(
            panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUmbralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUmbralLayout.createSequentialGroup()
                        .addComponent(lblUmbral)
                        .addGap(0, 514, Short.MAX_VALUE))
                    .addGroup(panelUmbralLayout.createSequentialGroup()
                        .addGroup(panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUmbralLayout.createSequentialGroup()
                                .addComponent(separatorUmbralResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAyuda))
                            .addGroup(panelUmbralLayout.createSequentialGroup()
                                .addComponent(txtUmbral, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEstablecer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblError)))
                        .addContainerGap())))
        );
        panelUmbralLayout.setVerticalGroup(
            panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUmbralLayout.createSequentialGroup()
                .addComponent(lblUmbral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUmbral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstablecer)
                    .addComponent(lblError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separatorUmbralResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAyuda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelUmbral, java.awt.BorderLayout.PAGE_START);

        panelResultado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 10, 10));

        txtValores.setEditable(false);
        txtValores.setColumns(20);
        txtValores.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        txtValores.setLineWrap(true);
        txtValores.setRows(5);
        scrollValores.setViewportView(txtValores);

        checkOrdenar.setSelected(true);
        checkOrdenar.setText("Ordenar de mayor a menor");
        checkOrdenar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkOrdenarStateChanged(evt);
            }
        });

        lblValores.setText("Valores menores que el umbral");

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addComponent(scrollValores)
                        .addContainerGap())
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValores)
                            .addComponent(checkOrdenar))
                        .addGap(0, 360, Short.MAX_VALUE))))
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addComponent(lblValores)
                .addGap(12, 12, 12)
                .addComponent(scrollValores, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOrdenar)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(panelResultado, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstablecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstablecerMouseClicked
        if (isNumeric(txtUmbral.getText())) {
            mostrarResultado();
        } else {
            lblError.setText("Por favor, introduzca un número real.");
        }
    }//GEN-LAST:event_btnEstablecerMouseClicked

    private void checkOrdenarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkOrdenarStateChanged
        if (checkOrdenar.isSelected()) {
            txtValores.setText(App.getVector().mostrarVector(true, true));
        } else {
            txtValores.setText(App.getVector().mostrarVector(true, false));
        }
    }//GEN-LAST:event_checkOrdenarStateChanged

    private void txtUmbralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUmbralKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnEstablecerMouseClicked(null);
        }
    }//GEN-LAST:event_txtUmbralKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstablecer;
    private javax.swing.JCheckBox checkOrdenar;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblUmbral;
    private javax.swing.JLabel lblValores;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JPanel panelUmbral;
    private javax.swing.JScrollPane scrollValores;
    private javax.swing.JSeparator separatorUmbralResultado;
    private javax.swing.JTextField txtUmbral;
    private javax.swing.JTextArea txtValores;
    // End of variables declaration//GEN-END:variables

    private void mostrarResultado() {
        Vector vector = App.getVector();
        OperacionesVector.buscaMenores(vector, Long.parseLong(txtUmbral.getText()));

        if (checkOrdenar.isSelected()) {
            txtValores.setText(vector.mostrarVector(true, true));
        } else {
            txtValores.setText(vector.mostrarVector(true, false));
        }
    }

    private boolean isNumeric(String input) {
        NumberFormat formatter = NumberFormat.getInstance();
        ParsePosition pos = new ParsePosition(0);

        formatter.parseObject(input, pos);
        return input.length() == pos.getIndex();
    }
}
