public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUmbral = new javax.swing.JPanel();
        lblUmbral = new javax.swing.JLabel();
        txtUmbral = new javax.swing.JTextField();
        btnEstablecer = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        separatorUmbralResultado = new javax.swing.JSeparator();
        lblAyuda = new javax.swing.JLabel();
        panelResultado = new javax.swing.JPanel();
        scrollValores = new javax.swing.JScrollPane();
        txtValores = new javax.swing.JTextArea();
        checkOrdenar = new javax.swing.JCheckBox();
        lblValores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Valores menores que un umbral");
        setResizable(false);

        panelUmbral.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 10));

        lblUmbral.setText("Umbral");

        btnEstablecer.setText("Establecer");

        lblError.setForeground(new java.awt.Color(206, 0, 0));
        lblError.setText("oulululililiu");

        separatorUmbralResultado.setForeground(new java.awt.Color(185, 185, 185));

        lblAyuda.setText("?");

        javax.swing.GroupLayout panelUmbralLayout = new javax.swing.GroupLayout(panelUmbral);
        panelUmbral.setLayout(panelUmbralLayout);
        panelUmbralLayout.setHorizontalGroup(
            panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUmbralLayout.createSequentialGroup()
                .addGroup(panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUmbralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separatorUmbralResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAyuda))
                    .addGroup(panelUmbralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUmbral)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
            .addGroup(panelUmbralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUmbral, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstablecer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(lblError)
                .addContainerGap())
        );
        panelUmbralLayout.setVerticalGroup(
            panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUmbralLayout.createSequentialGroup()
                .addComponent(lblUmbral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUmbral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstablecer)
                    .addComponent(lblError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUmbralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAyuda)
                    .addGroup(panelUmbralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(separatorUmbralResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelUmbral, java.awt.BorderLayout.PAGE_START);

        panelResultado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 10, 10));

        txtValores.setEditable(false);
        txtValores.setColumns(20);
        txtValores.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        txtValores.setLineWrap(true);
        txtValores.setRows(5);
        scrollValores.setViewportView(txtValores);

        checkOrdenar.setSelected(true);
        checkOrdenar.setText("Ordenar de mayor a menor");

        lblValores.setText("Valores menores que el umbral");

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addComponent(scrollValores)
                        .addGap(12, 12, 12))
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValores)
                            .addComponent(checkOrdenar))
                        .addGap(0, 364, Short.MAX_VALUE))))
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addComponent(lblValores)
                .addGap(12, 12, 12)
                .addComponent(scrollValores, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOrdenar)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(panelResultado, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstablecer;
    private javax.swing.JCheckBox checkOrdenar;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblUmbral;
    private javax.swing.JLabel lblValores;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JPanel panelUmbral;
    private javax.swing.JScrollPane scrollValores;
    private javax.swing.JSeparator separatorUmbralResultado;
    private javax.swing.JTextField txtUmbral;
    private javax.swing.JTextArea txtValores;
    // End of variables declaration//GEN-END:variables
}
